name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - run: npm ci

      - run: npm run lint:ci

      - name: Test
        env:
          MONGO_URI: ${{ secrets.TEST_MONGO_URI }}
        run: npm test
